

# tencent
host, mlvbdc.live.qcloud.com, Advertising
host-keyword, fusion.qq.com, Advertising
host-keyword, myqcloud, Advertising
host, cgi.connect.qq.com, Advertising
host, oth.bls.mdt.qq.com, Advertising
host, shortconn.im.qcloud.com, Advertising

HOST-SUFFIX, news.ssp.qq.com, Advertising
HOST-SUFFIX, news.l.qq.com, Advertising
HOST-SUFFIX, activeqq.3g.qq.com, Advertising
HOST-SUFFIX, ad.qq.com, Advertising
HOST-SUFFIX, adping.qq.com, Advertising
HOST-SUFFIX, adpm.app.qq.com, Advertising
HOST-SUFFIX, adrdir.qq.com, Advertising
HOST-SUFFIX, adsclick.qq.com, Advertising
HOST-SUFFIX, adsense.html5.qq.com, Advertising
HOST-SUFFIX, adsfile.qq.com, Advertising
HOST-SUFFIX, adsgroup.qq.com, Advertising
HOST-SUFFIX, adshmct.qq.com, Advertising
HOST-SUFFIX, adshmmsg.qq.com, Advertising
HOST-SUFFIX, adslvfile.qq.com, Advertising
HOST-SUFFIX, adslvseed.qq.com, Advertising
HOST-SUFFIX, adsolution.imtt.qq.com, Advertising
HOST-SUFFIX, adsqqclick.qq.com, Advertising
HOST-SUFFIX, adstextview.qq.com, Advertising
HOST-SUFFIX, adsview.qq.com, Advertising
HOST-SUFFIX, adsview2.qq.com, Advertising
HOST-SUFFIX, adv.app.qq.com, Advertising
HOST-SUFFIX, adver.qq.com, Advertising
HOST-SUFFIX, aeventlog.beacon.qq.com, Advertising
HOST-SUFFIX, analy.qq.com, Advertising
HOST-SUFFIX, astrategy.beacon.qq.com, Advertising
HOST-SUFFIX, c.gdt.qq.com, Advertising
HOST-SUFFIX, c.gj.qq.com, Advertising
HOST-SUFFIX, canvas.gdt.qq.com, Advertising
HOST-SUFFIX, d.gdt.qq.com, Advertising
HOST-SUFFIX, d3g.qq.com, Advertising
HOST-SUFFIX, download.sj.qq.com, Advertising
HOST-SUFFIX, dp3.qq.com, Advertising
HOST-SUFFIX, eventlog.beacon.qq.com, Advertising
HOST-SUFFIX, game.html5.qq.com, Advertising
HOST-SUFFIX, ggmmqq.com, Advertising
HOST-SUFFIX, j.wit.qq.com, Advertising
HOST-SUFFIX, jqmt.qq.com, Advertising
HOST-SUFFIX, jrlt.beacon.qq.com, Advertising
HOST-SUFFIX, jsqmt.qq.com, Advertising
HOST-SUFFIX, lives.l.qq.com, Advertising
HOST-SUFFIX, livep.l.qq.com, Advertising
HOST-SUFFIX, mi.gdt.qq.com, Advertising
HOST-SUFFIX, livep.l.ott.video.qq.com, Advertising
HOST-SUFFIX, lives.l.ott.video.qq.com, Advertising
HOST-SUFFIX, masdk.3g.qq.com, Advertising
HOST-SUFFIX, mfm.video.qq.com, Advertising
HOST-SUFFIX, mini2015.qq.com, Advertising
HOST-SUFFIX, monitor.uu.qq.com, Advertising
HOST-SUFFIX, mqqad.cs0309.html5.qq.com, Advertising
HOST-SUFFIX, mqqad.html5.qq.com, Advertising
HOST-SUFFIX, mqqadr.reader.qq.com, Advertising
HOST-SUFFIX, nc.gdt.qq.com, Advertising
HOST-SUFFIX, news.mpush.qq.com, Advertising
HOST-SUFFIX, news-l.play.ott.video.qq.com, Advertising
HOST-SUFFIX, novelsns.html5.qq.com, Advertising
HOST-SUFFIX, oth.update.mdt.qq.com, Advertising
HOST-SUFFIX, pcbrowser.dd.qq.com, Advertising
HOST-SUFFIX, pmir.3g.qq.com, Advertising
HOST-SUFFIX, pvstat.html5.qq.com, Advertising
HOST-SUFFIX, q.i.gdt.qq.com, Advertising
HOST-SUFFIX, qqshow2-item.qq.com, Advertising
HOST-SUFFIX, rm.gdt.qq.com, Advertising
HOST-SUFFIX, scdown.qq.com, Advertising
HOST-SUFFIX, setting.snswin.qq.com, Advertising
HOST-SUFFIX, sngmta.qq.com, Advertising
HOST-SUFFIX, strategy.beacon.qq.com, Advertising
HOST-SUFFIX, t.gdt.qq.com, Advertising
HOST-SUFFIX, t.sj.qq.com, Advertising
HOST-SUFFIX, ta.qq.com, Advertising
HOST-SUFFIX, tcss.qq.com, Advertising
HOST-SUFFIX, tpush.html5.qq.com, Advertising
HOST-SUFFIX, updatecenter.qq.com, Advertising
HOST-SUFFIX, video.ureport.push.qq.com, Advertising
HOST-SUFFIX, video.wap.mpush.qq.com, Advertising
HOST-SUFFIX, vlive.qqvideo.tc.qq.com, Advertising
HOST-SUFFIX, wap.mpush.qq.com, Advertising
HOST-SUFFIX, win.gdt.qq.com, Advertising
HOST-SUFFIX, ws.sj.qq.com, Advertising
HOST-SUFFIX, wxsnsdy.tc.qq.com, Advertising
HOST-SUFFIX, wxsnsdy.video.qq.com, Advertising
HOST-SUFFIX, adsmind.tc.qq.com, Advertising
HOST-SUFFIX, btrace.qq.com, Advertising
HOST-SUFFIX, mtrace.qq.com, Advertising
HOST-SUFFIX, pingma.qq.com, Advertising
HOST-SUFFIX, pingtcss.qq.com, Advertising
HOST-SUFFIX, tajs.qq.com, Advertising
HOST-SUFFIX, wxsnsdy.wxs.qq.com, Advertising
HOST-SUFFIX, wxsnsdythumb.wxs.qq.com, Advertising
HOST-SUFFIX, fusion.qq.com, Advertising
HOST-SUFFIX, ios.bugly.qq.com, Advertising
HOST, safebrowsing.urlsec.qq.com, Advertising
HOST-SUFFIX, oth.str.mdt.qq.com, Advertising
HOST-SUFFIX, l.qq.com, Advertising
HOST, adsmind.apdcdn.tc.qq.com, Advertising
HOST, adsmind.tc.qq.com, Advertising
HOST, adsmind.ugdtimg.com, Advertising
HOST, livep.l.t002.ottcn.com, Advertising
HOST, pgdt.ugdtimg.com, Advertising
HOST, splashqqlive.gtimg.com, Advertising
HOST, vv.video.qq.com, Advertising
HOST, wa.gtimg.com, Advertising
#HOST, wxsnsdy.wxs.qq.com, Advertising
#HOST, wxsnsdythu
